name: giftpose
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.7.2
  cached_network_image: ^3.4.1
  client_information: ^2.2.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  dio: ^5.9.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  flutter_multi_formatter: ^2.13.7
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: null
  flutter_svg: ^2.2.3
  get: ^4.7.3
  get_it: ^9.2.1
  hive_flutter: ^1.1.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  jiffy: ^6.4.3
  location: ^8.0.1
  locator: ^0.0.0-dev.2
  logger: ^2.6.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.11.1
  flutter_gen_runner: null
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Urbanist/Urbanist-VariableFont_wght.ttf
          style: italic
