import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:giftpose/services/database/database_service.dart';
import 'package:giftpose/utils/locator.dart';

class AppTranslations {
  static Map<String, Map<String, String>> translations = {
    'en': {
         "Tram":"Tram",
       "Train":"Train",          
       "Underground":"Underground",
       "Bus":"Bus",
       "Cycling":"Cycling",
       "Walking":"Walking",
       "Vehicle":"Vehicle",
       "Public Transport":"Public Transport",
       "Private Vehicle":"Private Vehicle",
       "miles away":"miles away",
      "Sign Up":"Sign Up",
      "Do not have an Account?":"Do not have an Account?",
      "Back to Login":"Back to Login",
      "Reset Password":"Reset Password",
      "Send Code":"Send Code",
      "Enter Code":"Enter Code",
      "Password Changed":"Password Changed",
      "Forgot Password":"Forgot Password",
      "Submit":"Submit",
      "Send code again:":"Send code again:",
      "Your password has been updated successfully. Please log in with your new password.":"Your password has been updated successfully. Please log in with your new password.",
      "Or Sign Up with":"Or Sign Up with",
  "Already have an account? ":"Already have an account? ",
  "Log In":"Log In",
      "1mi": "1mi",
       "Welcome Back": "Welcome Back",
"Enter your full name":"Enter your full name",
"Full Name":"Full Name",
"Enter your username":"Enter your username",
"Username":"Username",
"Enter your email address":"Enter your email address",
"Enter your password":"Enter your password",
"Password":"Password",
"Enter your confirm password":"Enter your confirm password",
"Confirm Password":"Confirm Password",
      "Yes": "Yes",
      "Choose a cause": "Choose a cause",
      "App Settings": "App Settings",
      "Articles": "Articles",
      "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. All rights reserved.",
      "Follow Us": "Follow Us",
      "Smart Assistant": "Smart Assistant",
      "GiftPose connects you to the gifts you need": "GiftPose connects you to the gifts you need",
      "\${vm.fetchItemsByIdMeResponse.data?.data?.distanceInMiles ?? 0} miles away": "\${vm.fetchItemsByIdMeResponse.data?.data?.distanceInMiles ?? 0} miles away",
      "Spreading joy through thoughtful, personalized giving.": "Spreading joy through thoughtful, personalized giving.",
      "Notification": "Notification",
      "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
      "Choose your Preferred Language": "Choose your Preferred Language",
      "Global Search": "Global Search",
      "English": "English",
      "Step-by-step guide to making a gift.": "Step-by-step guide to making a gift.",
      "\${location}ins": "\${location}ins",
      "Location": "Location",
      "Notification Alert": "Notification Alert",
      "Our support team is available 24/7 for inquiries.": "Our support team is available 24/7 for inquiries.",
      "Help Center": "Help Center",
      "No route defined for \${settings.name}": "No route defined for \${settings.name}",
      "Error: ": "Error: ",
      "Notification Alert Settings": "Notification Alert Settings",
      "Fundraising and financial gifts": "Fundraising and financial gifts",
      "Last updated: Oct 24, 2023": "Last updated: Oct 24, 2023",
      " GiftPose": " GiftPose",
      "Still need help?": "Still need help?",
      "GiftPose asks for your consent to use your personal data to:": "GiftPose asks for your consent to use your personal data to:",
      "25mi": "25mi",
      "Learn about fundraising, managing your gifts, and tax documentation.": "Learn about fundraising, managing your gifts, and tax documentation.",
      "Let our AI assistant notify you with similar items.": "Let our AI assistant notify you with similar items.",
      "No items available": "No items available",
      "Push Notifications": "Push Notifications",
      "Welcome": "Welcome",
      "Notifications": "Notifications",
      "Version 1.2.0": "Version 1.2.0",
      "Language": "Language",
      "Try adjusting your search or location": "Try adjusting your search or location",
      "Current Location": "Current Location",
      "No Notification Preference Set Yet": "No Notification Preference Set Yet",
      "Our Mission": "Our Mission",
      "About Gift Pose": "About Gift Pose",
      "Get notified on product of interest": "Get notified on product of interest",
      "How to donate": "How to donate",
      "Dark Mode": "Dark Mode",
      "Allow Notification": "Allow Notification",
      "Gift Details": "Gift Details",
      "Get timely updated and never miss out": "Get timely updated and never miss out",
      "How far are you willing to travel?": "How far are you willing to travel?",
      "Was this article helpful?": "Was this article helpful?",
      "No": "No",
      "Error: Try again": "Error: Try again",
      "How to ask for support": "How to ask for support",
      "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.",
      "50mi": "50mi",
      "How can we help?": "How can we help?",
      "Support": "Support",
      "Frequently Asked Questions": "Frequently Asked Questions",
      "Set Location": "Set Location",
      "Sending and receiving items": "Sending and receiving items",
      "v1.0.0": "v1.0.0",
      "No items found": "No items found",
      "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} miles",
      "Create an Account": "Create an Account",
      "Requesting": "Requesting",
      "All Gifts": "All Gifts",
      "About GiftPose": "About GiftPose",
      "Try adjusting your search": "Try adjusting your search",
      "Getting Gifts Closer to you...": "Getting Gifts Closer to you...",
      "Copied to clipboard": "Copied to clipboard",
      "Retry": "Retry",
      "Contact Support": "Contact Support",
      "Categories": "Categories",
      "Recieving": "Recieving",
      "Settings": "Settings",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ",
      "Gifting": "Gifting",
    },
    'de': {
"Visit Freebies": "Gratis-Angebote ansehen",
  "Mark as Taken": "Als genommen markieren",
        "Tram":"Straßenbahn",
       "Train":"Zug",          
       "Underground":"U-Bahn",
       "Bus":"Bus",
       "Cycling":"Radfahren",
       "Walking":"Zu Fuß",
       "Vehicle":"Vehicle",
       "Public Transport":"Öffentliche Verkehrsmittel",
       "Private Vehicle":"Privatfahrzeug",
       "miles away":"Meilen entfernt",
      "Do not have an Account?":"Sie haben kein Konto?",
      "Back to Login":"Zurück zum Login",
      "Reset Password":"Passwort zurücksetzen",
      "Send Code":"Code senden",
      "Enter Code":"Code eingeben",
      "Password Changed":"Passwort geändert",
      "Forgot Password":"Passwort vergessen",
      "Submit":"Senden",
      "Send code again:":"Code erneut senden:",
      "Your password has been updated successfully. Please log in with your new password.":"Ihr Passwort wurde erfolgreich zurückgesetzt. Bitte melden Sie sich mit Ihrem neuen Passwort an.",
      "Sign Up":"Registrieren",
      "Or Sign Up with":"Oder registrieren Sie sich mit",
  "Already have an account? ":"Sie haben bereits ein Konto? ",
  "Log In":"Anmelden",
       "Welcome Back": "Willkommen zurück",
"Enter your full name":"Geben Sie Ihren vollständigen Namen ein",
"Full Name":"Vollständiger Name",
"Enter your username":"Geben Sie Ihren Benutzernamen ein",
"Username":"Benutzername",
"Enter your email address":"Geben Sie Ihre E-Mail-Adresse ein",
"Enter your password":"Geben Sie Ihr Passwort ein",
"Password":"Passwort",
"Enter your confirm password":"Geben Sie Ihr Passwort erneut ein",
"Confirm Password":"Passwort bestätigen",
  "Welcome Back": "Willkommen zurück",
  "1mi": "1 mi",
  "Yes": "Ja",
  "Choose a cause": "Wählen Sie eine Sache",
  "App Settings": "App-Einstellungen",
  "Articles": "Artikel",
  "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. Alle Rechte vorbehalten.",
  "Follow Us": "Folgen Sie uns",
  "Smart Assistant": "Intelligenter Assistent",
  "GiftPose connects you to the gifts you need": "GiftPose verbindet Sie mit den Geschenken, die Sie benötigen",
  "Spreading joy through thoughtful, personalized giving.": "Freude verbreiten durch durchdachte, personalisierte Geschenke.",
  "Notification": "Benachrichtigung",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
  "Choose your Preferred Language": "Wählen Sie Ihre bevorzugte Sprache",
  "Global Search": "Globale Suche",
  "English": "Englisch",
  "Step-by-step guide to making a gift.": "Schritt-für-Schritt-Anleitung zum Erstellen eines Geschenks.",
  "\${location}ins": "\${location}",
  "Location": "Standort",
  "Notification Alert": "Benachrichtigungsalarm",
  "Our support team is available 24/7 for inquiries.": "Unser Support-Team ist rund um die Uhr für Anfragen verfügbar.",
  "Help Center": "Hilfezentrum",
  "No route defined for \${settings.name}": "Keine Route definiert für \${settings.name}",
  "Error: ": "Fehler: ",
  "Notification Alert Settings": "Benachrichtigungseinstellungen",
  "Fundraising and financial gifts": "Spendenaktionen und finanzielle Geschenke",
  "Last updated: Oct 24, 2023": "Zuletzt aktualisiert: 24. Okt. 2023",
  " GiftPose": " GiftPose",
  "Still need help?": "Benötigen Sie noch Hilfe?",
  "GiftPose asks for your consent to use your personal data to:": "GiftPose bittet um Ihre Zustimmung zur Verwendung Ihrer persönlichen Daten für:",
  "25mi": "25 mi",
  "Learn about fundraising, managing your gifts, and tax documentation.": "Erfahren Sie mehr über Spendenaktionen, die Verwaltung Ihrer Geschenke und Steuerdokumente.",
  "Let our AI assistant notify you with similar items.": "Lassen Sie sich von unserem KI-Assistenten über ähnliche Artikel informieren.",
  "No items available": "Keine Artikel verfügbar",
  "Push Notifications": "Push-Benachrichtigungen",
  "Welcome": "Willkommen",
  "Notifications": "Benachrichtigungen",
  "Version 1.2.0": "Version 1.2.0",
  "Language": "Sprache",
  "Try adjusting your search or location": "Versuchen Sie, Ihre Suche oder Ihren Standort anzupassen",
  "Current Location": "Aktueller Standort",
  "No Notification Preference Set Yet": "Noch keine Benachrichtigungseinstellungen festgelegt",
  "Our Mission": "Unsere Mission",
  "About Gift Pose": "Über GiftPose",
  "Get notified on product of interest": "Benachrichtigungen zu interessanten Produkten erhalten",
  "How to donate": "Wie man spendet",
  "Dark Mode": "Dunkelmodus",
  "Allow Notification": "Benachrichtigungen erlauben",
  "Gift Details": "Geschenkdetails",
  "Get timely updated and never miss out": "Erhalten Sie rechtzeitig Updates und verpassen Sie nichts",
  "How far are you willing to travel?": "Wie weit sind Sie bereit zu reisen?",
  "Was this article helpful?": "War dieser Artikel hilfreich?",
  "No": "Nein",
  "Error: Try again": "Fehler: Bitte versuchen Sie es erneut",
  "How to ask for support": "Wie man Support anfordert",
  "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "Durchsuchen Sie unsere verifizierte Liste gemeinnütziger Organisationen. Sie können nach Kategorien wie Bildung, Umwelt oder Gesundheit filtern, um eine passende Mission zu finden.",
  "50mi": "50 mi",
  "How can we help?": "Wie können wir helfen?",
  "Support": "Support",
  "Frequently Asked Questions": "Häufig gestellte Fragen",
  "Set Location": "Standort festlegen",
  "Sending and receiving items": "Senden und Empfangen von Artikeln",
  "v1.0.0": "v1.0.0",
  "No items found": "Keine Artikel gefunden",
  "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} mi",
  "Create an Account": "Konto erstellen",
  "Requesting": "Wird angefordert",
  "All Gifts": "Alle Geschenke",
  "About GiftPose": "Über GiftPose",
  "Try adjusting your search": "Versuchen Sie, Ihre Suche anzupassen",
  "Getting Gifts Closer to you...": "Geschenke näher zu Ihnen bringen...",
  "Copied to clipboard": "In die Zwischenablage kopiert",
  "Retry": "Erneut versuchen",
  "Contact Support": "Support kontaktieren",
  "Categories": "Kategorien",
  "Recieving": "Empfangen",
  "Settings": "Einstellungen",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet",
  "Gifting": "Schenken",
},
   'zh': {
"Visit Freebies": "查看免费物品",
"Mark as Taken": "标记为已领取",
     "Tram": "有轨电车",
"Train": "火车",
"Underground": "地铁",
"Bus": "公交车",
"Cycling": "骑行",
"Walking": "步行",
"Vehicle": "车辆",
"Public Transport": "公共交通",
"Private Vehicle": "私家车",
"miles away": "英里外",
          "Do not have an Account?":"您没有账户吗？",
      "Back to Login":"返回登录",
      "Reset Password":"重置密码",
      "Send Code":"发送验证码",
      "Enter Code":"输入验证码",
      "Password Changed":"密码已更改",
      "Forgot Password":"忘记密码",
      "Submit":"提交",
      "Send code again:":"再次发送验证码:",
      "Your password has been updated successfully. Please log in with your new password.":"您的密码已成功重置。请使用新密码登录。",
    "Sign Up":"注册",
    "Or Sign Up with":"或者注册",
  "Already have an account? ":"您已经有账户了吗？ ",
  "Log In":"登录",
     "Welcome Back": "欢迎回来",
"Enter your full name":"输入您的全名",
"Full Name":"全名",
"Enter your username":"输入您的用户名",
"Username":"用户名",
"Enter your email address":"输入您的电子邮件地址",
"Enter your password":"输入您的密码",
"Password":"密码",
"Enter your confirm password":"输入您的确认密码",
"Confirm Password":"确认密码",
    "Welcome Back": "欢迎回来",
  "1mi": "1英里",
  "Yes": "是",
  "Choose a cause": "选择一个公益项目",
  "App Settings": "应用设置",
  "Articles": "文章",
  "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. 保留所有权利。",
  "Follow Us": "关注我们",
  "Smart Assistant": "智能助手",
  "GiftPose connects you to the gifts you need": "GiftPose 帮助您找到所需的礼物",
  "Spreading joy through thoughtful, personalized giving.": "通过用心且个性化的赠礼传递快乐。",
  "Notification": "通知",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
  "Choose your Preferred Language": "选择您的首选语言",
  "Global Search": "全局搜索",
  "English": "英语",
  "Step-by-step guide to making a gift.": "制作礼物的分步指南。",
  "\${location}ins": "\${location}",
  "Location": "位置",
  "Notification Alert": "通知提醒",
  "Our support team is available 24/7 for inquiries.": "我们的支持团队全天候为您提供帮助。",
  "Help Center": "帮助中心",
  "No route defined for \${settings.name}": "未为 \${settings.name} 定义路由",
  "Error: ": "错误：",
  "Notification Alert Settings": "通知提醒设置",
  "Fundraising and financial gifts": "筹款和资金捐赠",
  "Last updated: Oct 24, 2023": "最后更新：2023年10月24日",
  " GiftPose": " GiftPose",
  "Still need help?": "仍需要帮助吗？",
  "GiftPose asks for your consent to use your personal data to:": "GiftPose 请求您同意使用您的个人数据以：",
  "25mi": "25英里",
  "Learn about fundraising, managing your gifts, and tax documentation.": "了解筹款、礼物管理以及税务文件。",
  "Let our AI assistant notify you with similar items.": "让我们的AI助手为您推荐类似的物品。",
  "No items available": "暂无可用项目",
  "Push Notifications": "推送通知",
  "Welcome": "欢迎",
  "Notifications": "通知",
  "Version 1.2.0": "版本 1.2.0",
  "Language": "语言",
  "Try adjusting your search or location": "请尝试调整您的搜索或位置",
  "Current Location": "当前位置",
  "No Notification Preference Set Yet": "尚未设置通知偏好",
  "Our Mission": "我们的使命",
  "About Gift Pose": "关于 GiftPose",
  "Get notified on product of interest": "获取感兴趣产品的通知",
  "How to donate": "如何捐赠",
  "Dark Mode": "深色模式",
  "Allow Notification": "允许通知",
  "Gift Details": "礼物详情",
  "Get timely updated and never miss out": "及时获取更新，不错过任何内容",
  "How far are you willing to travel?": "您愿意出行多远？",
  "Was this article helpful?": "这篇文章对您有帮助吗？",
  "No": "否",
  "Error: Try again": "错误：请重试",
  "How to ask for support": "如何获取支持",
  "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "浏览我们经过验证的慈善机构列表。您可以按教育、环境或健康等类别筛选，找到符合您理念的项目。",
  "50mi": "50英里",
  "How can we help?": "我们如何帮助您？",
  "Support": "支持",
  "Frequently Asked Questions": "常见问题",
  "Set Location": "设置位置",
  "Sending and receiving items": "发送和接收物品",
  "v1.0.0": "v1.0.0",
  "No items found": "未找到项目",
  "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} 英里",
  "Create an Account": "创建账户",
  "Requesting": "请求中",
  "All Gifts": "所有礼物",
  "About GiftPose": "关于 GiftPose",
  "Try adjusting your search": "请尝试调整您的搜索",
  "Getting Gifts Closer to you...": "正在为您匹配更近的礼物...",
  "Copied to clipboard": "已复制到剪贴板",
  "Retry": "重试",
  "Contact Support": "联系支持",
  "Categories": "分类",
  "Recieving": "接收中",
  "Settings": "设置",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet",
  "Gifting": "赠送",
},
   'fr': {
"Visit Freebies": "Voir les cadeaux",
  "Mark as Taken": "Marquer comme pris",
   "Tram": "Tramway",
"Train": "Train",
"Underground": "Métro",
"Bus": "Bus",
"Cycling": "Vélo",
"Walking": "À pied",
"Vehicle": "Véhicule",
"Public Transport": "Transports en commun",
"Private Vehicle": "Véhicule privé",
"miles away": "miles de distance",
          "Do not have an Account?":"Vous n'avez pas de compte ?",
      "Back to Login":"Retour à la connexion",
      "Reset Password":"Réinitialiser le mot de passe",
      "Send Code":"Envoyer le code",
      "Enter Code":"Entrer le code",
      "Password Changed":"Mot de passe changé",
      "Forgot Password":"Mot de passe oublié",
      "Submit":"Soumettre",
      "Send code again:":"Envoyer le code à nouveau :",
      "Your password has been updated successfully. Please log in with your new password.":"Votre mot de passe a été modifié avec succès. Veuillez vous connecter avec votre nouveau mot de passe.",
    "Sign Up":"Inscrivez-vous",
    "Or Sign Up with":"Ou inscrivez-vous avec",
  "Already have an account? ":"Vous avez déjà un compte ? ",
  "Log In":"Se connecter",
    "Welcome Back": "Bienvenue",
"Enter your full name":"Entrez votre nom complet",
"Full Name":"Nom complet",
"Enter your username":"Entrez votre nom d'utilisateur",
"Username":"Nom d'utilisateur",
"Enter your email address":"Entrez votre adresse e-mail",
"Enter your password":"Entrez votre mot de passe",
"Password":"Mot de passe",
"Enter your confirm password":"Entrez votre mot de passe de confirmation",
"Confirm Password":"Confirmer le mot de passe",
  "1mi": "1 mi",
  "Yes": "Oui",
  "Choose a cause": "Choisissez une cause",
  "App Settings": "Paramètres de l'application",
  "Articles": "Articles",
  "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. Tous droits réservés.",
  "Follow Us": "Suivez-nous",
  "Smart Assistant": "Assistant intelligent",
  "GiftPose connects you to the gifts you need": "GiftPose vous connecte aux cadeaux dont vous avez besoin",
  "Spreading joy through thoughtful, personalized giving.": "Diffuser la joie grâce à des dons réfléchis et personnalisés.",
  "Notification": "Notification",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
  "Choose your Preferred Language": "Choisissez votre langue préférée",
  "Global Search": "Recherche globale",
  "English": "Anglais",
  "Step-by-step guide to making a gift.": "Guide étape par étape pour faire un cadeau.",
  "\${location}ins": "\${location} à proximité",
  "Location": "Emplacement",
  "Notification Alert": "Alerte de notification",
  "Our support team is available 24/7 for inquiries.": "Notre équipe de support est disponible 24h/24 et 7j/7 pour vos questions.",
  "Help Center": "Centre d'aide",
  "No route defined for \${settings.name}": "Aucune route définie pour \${settings.name}",
  "Error: ": "Erreur : ",
  "Notification Alert Settings": "Paramètres des alertes de notification",
  "Fundraising and financial gifts": "Collecte de fonds et dons financiers",
  "Last updated: Oct 24, 2023": "Dernière mise à jour : 24 oct. 2023",
  " GiftPose": " GiftPose",
  "Still need help?": "Besoin d'aide supplémentaire ?",
  "GiftPose asks for your consent to use your personal data to:": "GiftPose demande votre consentement pour utiliser vos données personnelles afin de :",
  "25mi": "25 mi",
  "Learn about fundraising, managing your gifts, and tax documentation.": "Apprenez-en plus sur la collecte de fonds, la gestion de vos cadeaux et la documentation fiscale.",
  "Let our AI assistant notify you with similar items.": "Laissez notre assistant IA vous notifier des articles similaires.",
  "No items available": "Aucun article disponible",
  "Push Notifications": "Notifications push",
  "Welcome": "Bienvenue",
  "Notifications": "Notifications",
  "Version 1.2.0": "Version 1.2.0",
  "Language": "Langue",
  "Try adjusting your search or location": "Essayez d’ajuster votre recherche ou votre emplacement",
  "Current Location": "Emplacement actuel",
  "No Notification Preference Set Yet": "Aucune préférence de notification définie pour le moment",
  "Our Mission": "Notre mission",
  "About Gift Pose": "À propos de GiftPose",
  "Get notified on product of interest": "Recevez des notifications sur les produits qui vous intéressent",
  "How to donate": "Comment faire un don",
  "Dark Mode": "Mode sombre",
  "Allow Notification": "Autoriser les notifications",
  "Gift Details": "Détails du cadeau",
  "Get timely updated and never miss out": "Recevez des mises à jour en temps opportun et ne manquez rien",
  "How far are you willing to travel?": "Jusqu'où êtes-vous prêt à vous déplacer ?",
  "Was this article helpful?": "Cet article vous a-t-il été utile ?",
  "No": "Non",
  "Error: Try again": "Erreur : Réessayez",
  "How to ask for support": "Comment demander de l'aide",
  "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "Parcourez notre liste vérifiée d'organisations caritatives. Vous pouvez filtrer par catégorie comme l'éducation, l'environnement ou la santé pour trouver une mission qui vous correspond.",
  "50mi": "50 mi",
  "How can we help?": "Comment pouvons-nous vous aider ?",
  "Support": "Support",
  "Frequently Asked Questions": "Foire aux questions",
  "Set Location": "Définir l'emplacement",
  "Sending and receiving items": "Envoi et réception d'articles",
  "v1.0.0": "v1.0.0",
  "No items found": "Aucun article trouvé",
  "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} miles",
  "Create an Account": "Créer un compte",
  "Requesting": "Demande en cours",
  "All Gifts": "Tous les cadeaux",
  "About GiftPose": "À propos de GiftPose",
  "Try adjusting your search": "Essayez d’ajuster votre recherche",
  "Getting Gifts Closer to you...": "Rapprochement des cadeaux vers vous...",
  "Copied to clipboard": "Copié dans le presse-papiers",
  "Retry": "Réessayer",
  "Contact Support": "Contacter le support",
  "Categories": "Catégories",
  "Recieving": "Réception",
  "Settings": "Paramètres",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet",
  "Gifting": "Offrir",
},
    'it': {
      "Visit Freebies": "Visita Freebies",
"Mark as Taken": "Segna come preso",
"Tram": "Tram",
"Train": "Treno",
"Underground": "Metropolitana",
"Bus": "Autobus",
"Cycling": "Bicicletta",
"Walking": "A piedi",
"Vehicle": "Veicolo",
"Public Transport": "Trasporto pubblico",
"Private Vehicle": "Veicolo privato",
"miles away": "miglia di distanza",
"Visit Freebies": "Visita Freebies",
"Mark as Taken": "Segna come preso",
            "Do not have an Account?":"Non hai un account?",
      "Back to Login":"Torna al login",
      "Reset Password":"Reimposta password",
      "Send Code":"Invia codice",
      "Enter Code":"Inserisci codice",
      "Password Changed":"Password cambiata",
      "Forgot Password":"Password dimenticata",
      "Submit":"Invia",
      "Send code again:":"Invia codice di nuovo:",
      "Your password has been updated successfully. Please log in with your new password.":"La tua password è stata aggiornata con successo. Accedi con la tua nuova password.",
      "Sign Up":"Iscriviti",
      "Or Sign Up with":"O iscriviti con",
  "Already have an account? ":"Hai già un account? ",
  "Log In":"Accedi",
      "Welcome Back": "Benvenuto",
      "Enter your full name":"Inserisci il tuo nome completo",
"Full Name":"Nome completo",
"Enter your username":"Inserisci il tuo nome utente",
"Username":"Nome utente",
"Enter your email address":"Inserisci il tuo indirizzo email",
"Enter your password":"Inserisci la tua password",
"Password":"Password",
"Enter your confirm password":"Inserisci la tua password di conferma",
"Confirm Password":"Conferma password",
  "1mi": "1 mi",
  "Yes": "Sì",
  "Choose a cause": "Scegli una causa",
  "App Settings": "Impostazioni dell'app",
  "Articles": "Articoli",
  "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. Tutti i diritti riservati.",
  "Follow Us": "Seguici",
  "Smart Assistant": "Assistente intelligente",
  "GiftPose connects you to the gifts you need": "GiftPose ti connette ai regali di cui hai bisogno",
  "Spreading joy through thoughtful, personalized giving.": "Diffondiamo gioia attraverso doni attenti e personalizzati.",
  "Notification": "Notifica",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
  "Choose your Preferred Language": "Scegli la tua lingua preferita",
  "Global Search": "Ricerca globale",
  "English": "Inglese",
  "Step-by-step guide to making a gift.": "Guida passo dopo passo per fare un regalo.",
  "\${location}ins": "\${location} nelle vicinanze",
  "Location": "Posizione",
  "Notification Alert": "Avviso di notifica",
  "Our support team is available 24/7 for inquiries.": "Il nostro team di supporto è disponibile 24 ore su 24, 7 giorni su 7.",
  "Help Center": "Centro assistenza",
  "No route defined for \${settings.name}": "Nessun percorso definito per \${settings.name}",
  "Error: ": "Errore: ",
  "Notification Alert Settings": "Impostazioni avvisi di notifica",
  "Fundraising and financial gifts": "Raccolta fondi e donazioni finanziarie",
  "Last updated: Oct 24, 2023": "Ultimo aggiornamento: 24 ott 2023",
  " GiftPose": " GiftPose",
  "Still need help?": "Hai ancora bisogno di aiuto?",
  "GiftPose asks for your consent to use your personal data to:": "GiftPose richiede il tuo consenso per utilizzare i tuoi dati personali per:",
  "25mi": "25 mi",
  "Learn about fundraising, managing your gifts, and tax documentation.": "Scopri di più sulla raccolta fondi, la gestione dei regali e la documentazione fiscale.",
  "Let our AI assistant notify you with similar items.": "Consenti al nostro assistente AI di notificarti articoli simili.",
  "No items available": "Nessun articolo disponibile",
  "Push Notifications": "Notifiche push",
  "Welcome": "Benvenuto",
  "Notifications": "Notifiche",
  "Version 1.2.0": "Versione 1.2.0",
  "Language": "Lingua",
  "Try adjusting your search or location": "Prova a modificare la ricerca o la posizione",
  "Current Location": "Posizione attuale",
  "No Notification Preference Set Yet": "Nessuna preferenza di notifica impostata",
  "Our Mission": "La nostra missione",
  "About Gift Pose": "Informazioni su GiftPose",
  "Get notified on product of interest": "Ricevi notifiche sui prodotti di interesse",
  "How to donate": "Come donare",
  "Dark Mode": "Modalità scura",
  "Allow Notification": "Consenti notifiche",
  "Gift Details": "Dettagli del regalo",
  "Get timely updated and never miss out": "Ricevi aggiornamenti tempestivi e non perdere nulla",
  "How far are you willing to travel?": "Quanto lontano sei disposto a viaggiare?",
  "Was this article helpful?": "Questo articolo è stato utile?",
  "No": "No",
  "Error: Try again": "Errore: Riprova",
  "How to ask for support": "Come richiedere supporto",
  "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "Sfoglia il nostro elenco verificato di organizzazioni benefiche. Puoi filtrare per categoria come istruzione, ambiente o salute per trovare una missione che ti rappresenti.",
  "50mi": "50 mi",
  "How can we help?": "Come possiamo aiutarti?",
  "Support": "Supporto",
  "Frequently Asked Questions": "Domande frequenti",
  "Set Location": "Imposta posizione",
  "Sending and receiving items": "Invio e ricezione di articoli",
  "v1.0.0": "v1.0.0",
  "No items found": "Nessun articolo trovato",
  "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} miglia",
  "Create an Account": "Crea un account",
  "Requesting": "Richiesta in corso",
  "All Gifts": "Tutti i regali",
  "About GiftPose": "Informazioni su GiftPose",
  "Try adjusting your search": "Prova a modificare la ricerca",
  "Getting Gifts Closer to you...": "Avvicinando i regali a te...",
  "Copied to clipboard": "Copiato negli appunti",
  "Retry": "Riprova",
  "Contact Support": "Contatta il supporto",
  "Categories": "Categorie",
  "Recieving": "Ricezione",
  "Settings": "Impostazioni",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet",
  "Gifting": "Fare regali",
},
   'es': {

  "visit_freebies": "Ver objetos gratis",
  "mark_as_taken": "Marcar como entregado",

"Tram": "Tranvía",
"Train": "Tren",
"Underground": "Metro",
"Bus": "Autobús",
"Cycling": "Bicicleta",
"Walking": "A pie",
"Vehicle": "Vehículo",
"Public Transport": "Transporte público",
"Private Vehicle": "Vehículo privado",
"miles away": "millas de distancia",
            "Do not have an Account?":"¿No tienes una cuenta?",
      "Back to Login":"Volver al inicio de sesión",
      "Reset Password":"Restablecer contraseña",
      "Send Code":"Enviar código",
      "Enter Code":"Ingresar código",
      "Password Changed":"Contraseña cambiada",
      "Forgot Password":"Contraseña olvidada",
      "Submit":"Enviar",
      "Send code again:":"Enviar código de nuevo:",
      "Your password has been updated successfully. Please log in with your new password.":"Su contraseña ha sido actualizada exitosamente. Por favor, inicie sesión con su nueva contraseña.",
    "Sign Up":"Inscríbete",
    "Or Sign Up with":"O inscríbete con",
  "Already have an account? ":"¿Ya tienes una cuenta? ",
  "Log In":"Iniciar sesión",
    "Welcome Back": "Bienvenido",
    "Enter your full name":"Ingrese su nombre completo",
"Full Name":"Nombre completo",
"Enter your username":"Ingrese su nombre de usuario",
"Username":"Nombre de usuario",
"Enter your email address":"Ingrese su dirección de correo electrónico",
"Enter your password":"Ingrese su contraseña",
"Password":"Contraseña",
"Enter your confirm password":"Ingrese su contraseña de confirmación",
"Confirm Password":"Confirmar contraseña",
  "1mi": "1 mi",
  "Yes": "Sí",
  "Choose a cause": "Elige una causa",
  "App Settings": "Configuración de la aplicación",
  "Articles": "Artículos",
  "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. Todos los derechos reservados.",
  "Follow Us": "Síguenos",
  "Smart Assistant": "Asistente inteligente",
  "GiftPose connects you to the gifts you need": "GiftPose te conecta con los regalos que necesitas",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.distanceInMiles ?? 0} miles away": "\${vm.fetchItemsByIdMeResponse.data?.data?.distanceInMiles ?? 0} millas de distancia",
  "Spreading joy through thoughtful, personalized giving.": "Difundiendo alegría a través de regalos personalizados y significativos.",
  "Notification": "Notificación",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
  "Choose your Preferred Language": "Elige tu idioma preferido",
  "Global Search": "Búsqueda global",
  "English": "Inglés",
  "Step-by-step guide to making a gift.": "Guía paso a paso para hacer un regalo.",
  "\${location}ins": "\${location}",
  "Location": "Ubicación",
  "Notification Alert": "Alerta de notificación",
  "Our support team is available 24/7 for inquiries.": "Nuestro equipo de soporte está disponible 24/7 para consultas.",
  "Help Center": "Centro de ayuda",
  "No route defined for \${settings.name}": "No hay ruta definida para \${settings.name}",
  "Error: ": "Error: ",
  "Notification Alert Settings": "Configuración de alertas de notificación",
  "Fundraising and financial gifts": "Recaudación de fondos y donaciones financieras",
  "Last updated: Oct 24, 2023": "Última actualización: 24 de oct. de 2023",
  " GiftPose": " GiftPose",
  "Still need help?": "¿Aún necesitas ayuda?",
  "GiftPose asks for your consent to use your personal data to:": "GiftPose solicita tu consentimiento para usar tus datos personales para:",
  "25mi": "25 mi",
  "Learn about fundraising, managing your gifts, and tax documentation.": "Aprende sobre recaudación de fondos, gestión de regalos y documentación fiscal.",
  "Let our AI assistant notify you with similar items.": "Permite que nuestro asistente de IA te notifique sobre artículos similares.",
  "No items available": "No hay artículos disponibles",
  "Push Notifications": "Notificaciones push",
  "Welcome": "Bienvenido",
  "Notifications": "Notificaciones",
  "Version 1.2.0": "Versión 1.2.0",
  "Language": "Idioma",
  "Try adjusting your search or location": "Intenta ajustar tu búsqueda o ubicación",
  "Current Location": "Ubicación actual",
  "No Notification Preference Set Yet": "Aún no se ha configurado ninguna preferencia de notificación",
  "Our Mission": "Nuestra misión",
  "About Gift Pose": "Sobre GiftPose",
  "Get notified on product of interest": "Recibe notificaciones sobre productos de interés",
  "How to donate": "Cómo donar",
  "Dark Mode": "Modo oscuro",
  "Allow Notification": "Permitir notificaciones",
  "Gift Details": "Detalles del regalo",
  "Get timely updated and never miss out": "Recibe actualizaciones a tiempo y no te pierdas nada",
  "How far are you willing to travel?": "¿Qué tan lejos estás dispuesto a viajar?",
  "Was this article helpful?": "¿Este artículo fue útil?",
  "No": "No",
  "Error: Try again": "Error: inténtalo de nuevo",
  "How to ask for support": "Cómo solicitar soporte",
  "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "Explora nuestra lista verificada de organizaciones benéficas. Puedes filtrar por categorías como educación, medio ambiente o salud para encontrar una causa que te identifique.",
  "50mi": "50 mi",
  "How can we help?": "¿Cómo podemos ayudarte?",
  "Support": "Soporte",
  "Frequently Asked Questions": "Preguntas frecuentes",
  "Set Location": "Establecer ubicación",
  "Sending and receiving items": "Envío y recepción de artículos",
  "v1.0.0": "v1.0.0",
  "No items found": "No se encontraron artículos",
  "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} millas",
  "Create an Account": "Crear una cuenta",
  "Requesting": "Solicitando",
  "All Gifts": "Todos los regalos",
  "About GiftPose": "Sobre GiftPose",
  "Try adjusting your search": "Intenta ajustar tu búsqueda",
  "Getting Gifts Closer to you...": "Acercando regalos hacia ti...",
  "Copied to clipboard": "Copiado al portapapeles",
  "Retry": "Reintentar",
  "Contact Support": "Contactar soporte",
  "Categories": "Categorías",
  "Recieving": "Recibiendo",
  "Settings": "Configuración",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet",
  "Gifting": "Regalar",
},
    'pt': {
"Visit Freebies": "Ver itens grátis",
"Mark as Taken": "Marcar como recolhido",
"Tram": "Elétrico",
"Train": "Trem",
"Underground": "Metrô",
"Bus": "Ônibus",
"Cycling": "Bicicleta",
"Walking": "A pé",
"Vehicle": "Veículo",
"Public Transport": "Transporte público",
"Private Vehicle": "Veículo privado",
"miles away": "milhas de distância",
"Visit Freebies": "Ver itens grátis",
"Mark as Taken": "Marcar como recolhido",
            "Do not have an Account?":"Não tem uma conta?",
      "Back to Login":"Voltar ao login",
      "Reset Password":"Redefinir senha",
      "Send Code":"Enviar código",
      "Enter Code":"Inserir código",
      "Password Changed":"Senha alterada",
      "Forgot Password":"Esqueceu a senha",
      "Submit":"Enviar",
      "Send code again:":"Enviar código novamente:",
      "Your password has been updated successfully. Please log in with your new password.":"Sua senha foi atualizada com sucesso. Por favor, faça login com sua nova senha.",
      "Sign Up":"Inscreva-se",
      "Or Sign Up with":"Ou inscreva-se com",
  "Already have an account? ":"Você já tem uma conta? ",
  "Log In":"Entrar",
      "Welcome Back": "Bem-vindo",
      "Enter your full name":"Digite seu nome completo",
"Full Name":"Nome completo",
"Enter your username":"Digite seu nome de usuário",
"Username":"Nome de usuário",
"Enter your email address":"Digite seu endereço de e-mail",
"Enter your password":"Digite sua senha",
"Password":"Senha",
"Enter your confirm password":"Digite sua senha de confirmação",
"Confirm Password":"Confirmar senha",
  "1mi": "1mi",
  "Yes": "Sim",
  "Choose a cause": "Escolha uma causa",
  "App Settings": "Configurações do aplicativo",
  "Articles": "Artigos",
  "© 2026 GiftPose Inc. All rights reserved.": "© 2026 GiftPose Inc. Todos os direitos reservados.",
  "Follow Us": "Siga-nos",
  "Smart Assistant": "Assistente Inteligente",
  "GiftPose connects you to the gifts you need": "O GiftPose conecta você aos presentes que você precisa",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.distanceInMiles ?? 0} miles away": "\${vm.fetchItemsByIdMeResponse.data?.data?.distanceInMiles ?? 0} milhas de distância",
  "Spreading joy through thoughtful, personalized giving.": "Espalhando alegria através de presentes personalizados e significativos.",
  "Notification": "Notificação",
  "\${vm.fetchItemsByIdMeResponse.data?.data?.description}": "\${vm.fetchItemsByIdMeResponse.data?.data?.description}",
  "Choose your Preferred Language": "Escolha seu idioma preferido",
  "Global Search": "Busca global",
  "English": "Inglês",
  "Step-by-step guide to making a gift.": "Guia passo a passo para fazer um presente.",
  "\${location}ins": "\${location}",
  "Location": "Localização",
  "Notification Alert": "Alerta de notificação",
  "Our support team is available 24/7 for inquiries.": "Nossa equipe de suporte está disponível 24/7 para dúvidas.",
  "Help Center": "Central de ajuda",
  "No route defined for \${settings.name}": "Nenhuma rota definida para \${settings.name}",
  "Error: ": "Erro: ",
  "Notification Alert Settings": "Configurações de alerta de notificação",
  "Fundraising and financial gifts": "Arrecadação de fundos e doações financeiras",
  "Last updated: Oct 24, 2023": "Última atualização: 24 de out. de 2023",
  " GiftPose": " GiftPose",
  "Still need help?": "Ainda precisa de ajuda?",
  "GiftPose asks for your consent to use your personal data to:": "O GiftPose solicita seu consentimento para usar seus dados pessoais para:",
  "25mi": "25mi",
  "Learn about fundraising, managing your gifts, and tax documentation.": "Aprenda sobre arrecadação de fundos, gerenciamento de presentes e documentação fiscal.",
  "Let our AI assistant notify you with similar items.": "Permita que nosso assistente de IA notifique você sobre itens semelhantes.",
  "No items available": "Nenhum item disponível",
  "Push Notifications": "Notificações push",
  "Welcome": "Bem-vindo",
  "Notifications": "Notificações",
  "Version 1.2.0": "Versão 1.2.0",
  "Language": "Idioma",
  "Try adjusting your search or location": "Tente ajustar sua busca ou localização",
  "Current Location": "Localização atual",
  "No Notification Preference Set Yet": "Nenhuma preferência de notificação definida ainda",
  "Our Mission": "Nossa missão",
  "About Gift Pose": "Sobre o GiftPose",
  "Get notified on product of interest": "Receba notificações sobre produtos de interesse",
  "How to donate": "Como doar",
  "Dark Mode": "Modo escuro",
  "Allow Notification": "Permitir notificações",
  "Gift Details": "Detalhes do presente",
  "Get timely updated and never miss out": "Receba atualizações em tempo real e não perca nada",
  "How far are you willing to travel?": "Até que distância você está disposto a viajar?",
  "Was this article helpful?": "Este artigo foi útil?",
  "No": "Não",
  "Error: Try again": "Erro: tente novamente",
  "How to ask for support": "Como solicitar suporte",
  "Browse our verified list of charitable organizations. You can filter by category such as education, environment, or health to find a mission that resonates with you.": "Explore nossa lista verificada de organizações beneficentes. Você pode filtrar por categorias como educação, meio ambiente ou saúde para encontrar uma causa que combine com você.",
  "50mi": "50mi",
  "How can we help?": "Como podemos ajudar?",
  "Support": "Suporte",
  "Frequently Asked Questions": "Perguntas frequentes",
  "Set Location": "Definir localização",
  "Sending and receiving items": "Envio e recebimento de itens",
  "v1.0.0": "v1.0.0",
  "No items found": "Nenhum item encontrado",
  "\${onboardVm.miles.toStringAsFixed(0)} miles": "\${onboardVm.miles.toStringAsFixed(0)} milhas",
  "Create an Account": "Criar uma conta",
  "Requesting": "Solicitando",
  "All Gifts": "Todos os presentes",
  "About GiftPose": "Sobre o GiftPose",
  "Try adjusting your search": "Tente ajustar sua busca",
  "Getting Gifts Closer to you...": "Trazendo presentes mais perto de você...",
  "Copied to clipboard": "Copiado para a área de transferência",
  "Retry": "Tentar novamente",
  "Contact Support": "Entrar em contato com o suporte",
  "Categories": "Categorias",
  "Recieving": "Recebendo",
  "Settings": "Configurações",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet ": "Lorem ipsum dolor sit amet, consectetur adipiscing elit purus sit amet",
  "Gifting": "Presentear",
},
  };
}

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'English';
  
  LanguageProvider() {
    _loadLanguage();
  }

  void _loadLanguage() {
    try {
      final savedLang = serviceLocator<DatabaseService>().getLanguage();
      if (savedLang != null && savedLang.isNotEmpty) {
        _currentLanguage = savedLang;
        notifyListeners();
      }
    } catch (e) {
      // Ignored if service locator is not fully ready
    }
  }
  
  String get currentLanguage => _currentLanguage;
  
  void setLanguage(String language) {
    _currentLanguage = language;
    serviceLocator<DatabaseService>().saveLanguage(language);
    notifyListeners();
  }
  
  String getLanguageCode() {
    switch (_currentLanguage) {
      case 'German': return 'de';
      case 'Chinese': return 'zh';
      case 'French': return 'fr';
      case 'Italian': return 'it';
      case 'Spanish': return 'es';
      case 'Portuguese': return 'pt';
      case 'English':
      default: return 'en';
    }
  }

  String translate(String key) {
    final code = getLanguageCode();
    return AppTranslations.translations[code]?[key] ?? key;
  }
}

extension TranslateExtension on String {
  String tr(BuildContext context) {
    return Provider.of<LanguageProvider>(context, listen: true).translate(this);
  }
}































